# Generated by Django 3.2.12 on 2024-07-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('token', models.CharField(max_length=32, verbose_name='2FA Token')),
                ('sul', models.CharField(max_length=150, verbose_name='Single Unified Login')),
                ('valid', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
