# Generated by Django 3.2.12 on 2024-04-05 08:55

from django.db import migrations, models
import ldapbackend.validators
import signups.validators


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0004_auto_20230825_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email address already in use.'}, help_text='Your email must be unique.               If you are setting up an account for a bot,               please use a dedicated email address or an              address suffix, e.g. user+bot@example.com              (if you mailserver supports this).', max_length=254, unique=True, validators=[ldapbackend.validators.LDAPEmailValidator], verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='uid',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Your shell username will be used when logging             into <a href="https://wikitech.wikimedia.org/wiki/Portal:Toolforge">Toolforge</a>,             other <a href="https://wikitech.wikimedia.org/wiki/Portal:Cloud_VPS">Wikimedia VPS</a>             or Wikimedia production hosts using <a href="https://en.wikipedia.org/wiki/Secure_Shell">SSH</a>.             This name is typically shorter than a wiki username. It must start with a-z, and can             only contain lowercase a-z, 0-9 and - characters.', max_length=32, null=True, unique=True, validators=[ldapbackend.validators.UnixUsernameRegExValidator(), ldapbackend.validators.unix_username_length_validator, signups.validators.UsernameValidator], verbose_name='SSH access (shell) username'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Developer account usernames are commonly either the same as             a user's Wikimedia account username or their real name.", max_length=150, unique=True, validators=[ldapbackend.validators.LDAPUsernameValidator, signups.validators.UsernameValidator, signups.validators.IsURLValidator], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='UserValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='username')),
                ('uid', models.CharField(max_length=32, verbose_name='SSH access (shell) username')),
                ('sanitized', models.CharField(max_length=150, verbose_name='sanitized')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
