---
services:
  ldap:
    build: ./docker/openldap/build
    image: docker-registry.wikimedia.org/dev/bullseye-openldap:1.0.7-dev
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-D", "cn=admin,dc=example,dc=org", "-w", "adminpassword", "-b", "dc=example,dc=org", "|", "grep", "-q", "cn=www"]
    ports:
      - "2389:389"
    volumes:
      - type: bind
        source: docker/openldap/test_data/
        target: /ldifs
    networks:
      default:
        aliases:
          - openldap.local.wmftest.net
  redis:
    image: redis:bullseye
    platform: linux/amd64
    ports:
      - "6379:6379"
    networks:
      default:
        aliases:
          - redis.local.wmftest.net
  db:
    image: mariadb
    platform: linux/amd64
    ports:
      - "3306:3306"
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: idm
      MARIADB_DATABASE: idm
      MARIADB_PASSWORD: secret
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 5s
      retries: 20
    networks:
      default:
        aliases:
          - db.local.wmftest.net

  cas:
    image: cas:7.2.4
    ports:
      - "8443:8443"
    links:
      - ldap
      - redis
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - type: bind
        source: docker/cas/config/
        target: /etc/cas/config/
      - type: bind
        source: docker/cas/keystore.jks
        target: /etc/cas/thekeystore
      - type: bind
        source: docker/cas/services/
        target: /etc/cas/services/
      - type: bind
        source: docker/cas/webauthn
        target: /etc/cas/webauthn
  bitu:
    build:
      context: .
      dockerfile: .pipeline/blubber.yaml
      target: production
    image: bitu/production
    ports:
      - "8080:8080"
    environment:
      DJANGO_SECRET_KEY: TESTING
      RQ_REDIS_HOST: redis
      LDAP_SERVER_URI: ldap://ldap:389
      LDAP_USER_DN: cn=admin,dc=example,dc=org
      LDAP_PASSWORD: adminpassword
      DATABASE_HOST: db
      DATABASE_USER: idm
      DATABASE_NAME: idm
      DATABASE_PASSWORD: secret
      DATABASE_ENGINE: django.db.backends.mysql
      UWSGI_HTTP_MODE: true
    depends_on:
      ldap:
        condition: service_started
      redis:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      default:
        aliases:
          - bitu.local.wmftest.net