# Generated by Django 3.2.12 on 2024-09-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlockEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('action', models.CharField(max_length=256)),
                ('comment', models.TextField()),
            ],
        ),
    ]
