# Generated by Django 3.2.12 on 2024-10-11 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikimedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblockeventlog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikimedia.userblockeventlog'),
        ),
    ]
