# Generated by Django 3.2.12 on 2025-09-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikimedia', '0002_userblockeventlog_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblockeventlog',
            name='unset_email',
            field=models.BooleanField(default=False),
        ),
    ]
