# Generated by Django 3.2.12 on 2023-06-15 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keymanagement.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('ldapbackend', 'Wikimedia Cloud Service SSH keys'), ('puppet', 'puppet'), ('', '')], default='', max_length=256)),
                ('ssh_public_key', models.TextField(unique=True, validators=[keymanagement.validators.SSHKeyValidator.validate])),
                ('comment', models.CharField(default='', max_length=256)),
                ('active', models.BooleanField(default=False)),
                ('key_type', models.CharField(default='', max_length=32, null=True)),
                ('key_size', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sshkey',
            constraint=models.UniqueConstraint(fields=('system', 'ssh_public_key', 'active'), name='unique_active_key'),
        ),
    ]
