# Generated by Django 3.2.12 on 2024-04-09 13:04

from django.db import migrations, models
import keymanagement.validators


class Migration(migrations.Migration):

    dependencies = [
        ('keymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshkey',
            name='ssh_public_key',
            field=models.TextField(unique=True, validators=[keymanagement.validators.ssh_key_validator]),
        ),
        migrations.AlterField(
            model_name='sshkey',
            name='system',
            field=models.CharField(blank=True, choices=[('', '---'), ('ldapbackend', 'Wikimedia Cloud Services')], default='', max_length=256),
        ),
    ]
