# Generated by Django 3.2.12 on 2024-04-12 12:10

from django.db import migrations, models
import keymanagement.validators


class Migration(migrations.Migration):

    dependencies = [
        ('keymanagement', '0002_auto_20240409_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshkey',
            name='ssh_public_key',
            field=models.TextField(unique=True, validators=[keymanagement.validators.ssh_key_validator, keymanagement.validators.ssh_key_usage_validator]),
        ),
    ]
