# Generated by Django 3.2.12 on 2024-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymanagement', '0003_alter_sshkey_ssh_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshkey',
            name='system',
            field=models.CharField(choices=[('ldapbackend', 'Wikimedia Cloud Services')], default='ldapbackend', max_length=256),
        ),
    ]
