# Generated by Django 3.2.12 on 2025-12-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymanagement', '0004_alter_sshkey_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshkey',
            name='key_type',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
