# Generated by Django 3.2.12 on 2023-05-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0002_blocklistusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklistusername',
            name='origin',
            field=models.CharField(default='manual', max_length=255),
        ),
    ]
