# Generated by Django 3.2.12 on 2023-04-17 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keymanagement.validators


class Migration(migrations.Migration):

    replaces = [('keymanagement', '0001_initial'), ('keymanagement', '0002_auto_20230314_0832'), ('keymanagement', '0003_auto_20230315_0824'), ('keymanagement', '0004_auto_20230315_1253'), ('keymanagement', '0005_auto_20230317_1253')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('ldapbackend', 'WMCS Public SSH key'), ('puppet', 'puppet'), ('', '')], default='', max_length=256)),
                ('comment', models.CharField(default='', max_length=256)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
                ('ssh_public_key', models.TextField(unique=True, validators=[keymanagement.validators.SSHKeyValidator.validate])),
                ('key_size', models.IntegerField(default=0)),
                ('key_type', models.CharField(default='', max_length=32, null=True)),
            ],
            options={
                'unique_together': {('user', 'system', 'active', 'ssh_public_key')},
            },
        ),
    ]
